apiVersion: v1
kind: Service
metadata:
  name: load-balancer
  labels:
    app: mtr-react-app
spec:
  type: LoadBalancer
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    nodePort: 30000
  selector:
    app: mtr-react-app